# #Server port
# server.port= 8900

# #Application name
# spring.application.name= api-gateway

# #Client registration options :
# eureka.client.service-url.defaultZone = http://localhost:8761/eureka

# zuul.prefix=/api
# zuul.ignored-services=*

# # Map paths to services
# #----------------------------------
# # User service :
# zuul.routes.userservice.path=/accounts/**
# zuul.routes.userservice.service-id=user-service

# # Catalog service :
# zuul.routes.catalogservice.path=/catalog/**
# zuul.routes.catalogservice.service-id=product-catalog-service

# # Order service :
# zuul.routes.orderservice.path=/shop/**
# zuul.routes.orderservice.service-id=order-service

# # Recommendation service :
# zuul.routes.recommendationservice.path=/review/**
# zuul.routes.recommendationservice.service-id=product-recommendation-service

# #SPRING SESSION & REDIS PROPERTIES :
# #-------------------------------
# spring.session.store-type=redis
# spring.session.redis.namespace=session
# spring.session.redis.flush-mode=on-save
# spring.redis.host=localhost
# spring.redis.port=6379
# spring.main.allow-bean-definition-overriding=true

# #SECURITY
# #---------------------------------
# zuul.sensitive-headers=


# Server port
server.port=8900

# Application name
spring.application.name=api-gateway

# Client registration options:
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# SPRING SESSION & REDIS PROPERTIES :
#-------------------------------
spring.session.store-type=redis
spring.session.redis.namespace=session
spring.session.redis.flush-mode=on-save
spring.redis.host=localhost
spring.redis.port=6379
spring.main.allow-bean-definition-overriding=true

# Map paths to services (THAY THẾ CHO ZUUL BẰNG STRIP_PREFIX)
#----------------------------------
# 1. User service :
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/accounts/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# 2. Catalog service :
spring.cloud.gateway.routes[1].id=product-catalog-service
spring.cloud.gateway.routes[1].uri=lb://product-catalog-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/catalog/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# 3. Order service :
spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=lb://order-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/shop/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# 4. Recommendation service :
spring.cloud.gateway.routes[3].id=product-recommendation-service
spring.cloud.gateway.routes[3].uri=lb://product-recommendation-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/review/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1