#Server port:
server.port=8815

#Application name:
spring.application.name=payment-service

#Client registration properties:
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#Data source - SQL Server Configuration:
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=orders;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=YourPassword123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

#Jpa/Hibernate:
spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=validate

#Stripe Configuration:
stripe.api.key=sk_test_YOUR_STRIPE_KEY_HERE
