##### Service details: #####
server.port=8811
spring.application.name=user-service
server.url=http://localhost:8811

#Client registration properties :
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#Data source - SQL Server Configuration :
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=users;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=YourPassword123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

#Jpa/Hibernate :
spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=validate

##### HTTP #####
error.404.schema.details=The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable
error.406.schema.details=This request is not acceptable. Supported MIME types are application/json
