#Server port:
server.port=8817

#Application name:
spring.application.name=virtual-assistant-service

#Client registration properties:
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#OpenAI Configuration:
openai.api.key=sk-your-openai-key-here
